"""Add file sharing and visibility features

Revision ID: 0b9b5b2ca0c4
Revises: 31f8f4083f29
Create Date: 2025-04-25 22:50:00.830878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9b5b2ca0c4'
down_revision = '31f8f4083f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_share',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'user_id')
    )
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    op.drop_table('file_share')
    # ### end Alembic commands ###
